# Name : Archana Rathore
# FavTutor Internship Assignment

### Import Required Libraries

In [1]:
import pandas as pd  # for data manipulation
import numpy as np # for mathematical computation

### Load and read the data set

In [2]:
df = pd.read_csv('processed.cleveland.data')

###  Reading the first five rows

In [3]:
df.head()

63.0  1.0  1.0.1  145.0  233.0  1.0.2  2.0  150.0  0.0  2.3  3.0 0.0.1  \
0  67.0  1.0    4.0  160.0  286.0    0.0  2.0  108.0  1.0  1.5  2.0   3.0   
1  67.0  1.0    4.0  120.0  229.0    0.0  2.0  129.0  1.0  2.6  2.0   2.0   
2  37.0  1.0    3.0  130.0  250.0    0.0  0.0  187.0  0.0  3.5  3.0   0.0   
3  41.0  0.0    2.0  130.0  204.0    0.0  2.0  172.0  0.0  1.4  1.0   0.0   
4  56.0  1.0    2.0  120.0  236.0    0.0  0.0  178.0  0.0  0.8  1.0   0.0   

   6.0  0  
0  3.0  2  
1  7.0  1  
2  3.0  0  
3  3.0  0  
4  3.0  0

In [4]:
# Rename the columns as given

In [5]:

# 1. #3 (age) 
# 2. #4 (sex) 
# 3. #9 (cp) 
# 4. #10 (trestbps) 
# 5. #12 (chol) 
# 6. #16 (fbs) 
# 7. #19 (restecg) 
# 8. #32 (restecg) 
# 9. #38 (exang) 
# 10. #40 (oldpeak) 
# 11. #41 (slope) 
# 12. #44 (ca) 
# 13. #51 (thal) 
# 14. #58 (num) (the predicted attribute) 

In [6]:
df.rename(columns = {'63.0' : 'age','1.0':'sex','1.0':'cp','145.0':'trestbps','233.0':'chol','1.0.2':'fbs','2.0':'restecg','150.0':'restecg','0.0':'exang','2.3':'oldpeak','3.0':'slope','0.0.1':'ca','6.0':'thal','0':'num'},inplace= True)

In [7]:
df

age   cp  1.0.1  trestbps   chol  fbs  restecg  restecg  exang  oldpeak  \
0    67.0  1.0    4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
1    67.0  1.0    4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
2    37.0  1.0    3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
3    41.0  0.0    2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   
4    56.0  1.0    2.0     120.0  236.0  0.0      0.0    178.0    0.0      0.8   
..    ...  ...    ...       ...    ...  ...      ...      ...    ...      ...   
297  45.0  1.0    1.0     110.0  264.0  0.0      0.0    132.0    0.0      1.2   
298  68.0  1.0    4.0     144.0  193.0  1.0      0.0    141.0    0.0      3.4   
299  57.0  1.0    4.0     130.0  131.0  0.0      0.0    115.0    1.0      1.2   
300  57.0  0.0    2.0     130.0  236.0  0.0      2.0    174.0    0.0      0.0   
301  38.0  1.0    3.0     138.0  175.0  0.0      0.0    173.0    0.0      0.0   

     slope   ca thal  num  
0      2.0  3.0  3.0    2  
1      2.0  2.0  7.0    1  
2      3.0  0.0  3.0    0  
3      1.0  0.0  3.0    0  
4      1.0  0.0  3.0    0  
..     ...  ...  ...  ...  
297    2.0  0.0  7.0    1  
298    2.0  2.0  7.0    2  
299    2.0  1.0  7.0    3  
300    2.0  1.0  3.0    1  
301    1.0    ?  3.0    0  

[302 rows x 14 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       302 non-null    float64
 1   cp        302 non-null    float64
 2   1.0.1     302 non-null    float64
 3   trestbps  302 non-null    float64
 4   chol      302 non-null    float64
 5   fbs       302 non-null    float64
 6   restecg   302 non-null    float64
 7   restecg   302 non-null    float64
 8   exang     302 non-null    float64
 9   oldpeak   302 non-null    float64
 10  slope     302 non-null    float64
 11  ca        302 non-null    object 
 12  thal      302 non-null    object 
 13  num       302 non-null    int64  
dtypes: float64(11), int64(1), object(2)
memory usage: 33.2+ KB


# Question 1

### 1.Currently the response variable is the 14th attribute. It has 5 different values: observations with non-zero values have heart disease; those with 0 values do not have heart disease. The goal of this assignment is to construct classification models to distinguish present and absence. Create a new response variable, y, such that: for observation with values 1,2,3,4 will have value 1, 0 otherwise. 
### Remove observations with missing values. 
### Create dummy variables for categorical variables if necessary. 

#### Part 1 . Create a new response variable, y, such that: for observation with values 1,2,3,4 will have value 1, 0 otherwise.

In [9]:
df['num'].value_counts()

0    163
1     55
2     36
3     35
4     13
Name: num, dtype: int64

In [10]:
df['num']=df['num'].replace([2,3,4] , 1)

In [11]:
df['num'].value_counts()

0    163
1    139
Name: num, dtype: int64

### Part 2 Missing values

In [12]:
df.isnull().sum()

age         0
cp          0
1.0.1       0
trestbps    0
chol        0
fbs         0
restecg     0
restecg     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
num         0
dtype: int64

#### Conclusion : there are no missing values therefore we do not need to drop any column

### Part 3 Create dummy variables for categorical variables if necessary.

#### column 'ca'

In [13]:
df['ca'].value_counts()

0.0    175
1.0     65
2.0     38
3.0     20
?        4
Name: ca, dtype: int64

In [14]:
index1 = np.where(df['ca']=='?')
index1

(array([165, 191, 286, 301], dtype=int64),)

In [15]:
df.drop([165, 191, 286, 301],axis = 0, inplace = True)

#### Converting object datatype values to float data type

In [16]:
df['ca'] = df['ca'].astype(float)

#### column 'thal'

In [17]:
df['thal'].value_counts()

3.0    164
7.0    115
6.0     17
?        2
Name: thal, dtype: int64

In [18]:
index2 = np.where(df['thal']=='?')

In [19]:
index2

(array([ 86, 263], dtype=int64),)

In [20]:
type(index2)

tuple

In [21]:
df.drop([ 86, 265],axis = 0, inplace = True)

In [22]:
df['thal'].value_counts()

3.0    164
7.0    115
6.0     17
Name: thal, dtype: int64

#### Converting object datatype values to float data type

In [23]:
df['thal'] = df['thal'].astype(float)

# Question 2.	Split the data set to training and testing with ratio 80:20. 

In [24]:
# DATASET SPLIT

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('num',axis=1), 
                                                    df['num'], test_size=0.2, 
                                                    random_state=101)

In [27]:
X_train.shape

(236, 13)

In [28]:
y_train.shape

(236,)

In [29]:
X_test.shape

(60, 13)

In [30]:
y_test.shape

(60,)

# Question 3 . 3.	Fit a logistic regression model using statsmodels.api. Interpret coefficients that are significant. 

In [31]:
# model fitting

In [32]:
from sklearn.linear_model import LogisticRegression

C:\Users\ARCHANA\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Users\ARCHANA\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=T

In [33]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)


C:\Users\ARCHANA\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
predictions = logmodel.predict(X_test)

C:\Users\ARCHANA\Anaconda3\lib\site-packages\sklearn\linear_model\base.py:291: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  indices = (scores > 0).astype(np.int)


In [35]:
predictions

array([0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

In [36]:
logmodel.score(X_test,y_test)

C:\Users\ARCHANA\Anaconda3\lib\site-packages\sklearn\linear_model\base.py:291: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  indices = (scores > 0).astype(np.int)


0.8833333333333333

# Question 5 5.	For each of threshold value a found in part 4, perform prediction on the test data set. Provide the confusion matrix and other metrics such TPR, FPR, TNR, FNR, accuracy, and precision. 

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy=accuracy_score(y_test,predictions)

In [39]:
from sklearn.metrics import classification_report

In [40]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.89      0.91      0.90        35
           1       0.88      0.84      0.86        25

    accuracy                           0.88        60
   macro avg       0.88      0.88      0.88        60
weighted avg       0.88      0.88      0.88        60



In [41]:
classifier = LogisticRegression()
y_score = classifier.fit(X_train, y_train).predict_proba(X_test)

C:\Users\ARCHANA\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [42]:
y_score.shape

(60, 2)

In [43]:
from sklearn.metrics import roc_curve
fpr, tpr, threshold = roc_curve(y_test, y_score[:,1])

# FPR

In [44]:
fpr

array([0.        , 0.        , 0.        , 0.02857143, 0.02857143,
       0.05714286, 0.05714286, 0.08571429, 0.08571429, 0.31428571,
       0.31428571, 0.65714286, 0.65714286, 1.        ])

# TPR

In [45]:
tpr

array([0.  , 0.04, 0.32, 0.32, 0.52, 0.52, 0.84, 0.84, 0.88, 0.88, 0.96,
       0.96, 1.  , 1.  ])

# Threshold

In [46]:
threshold

array([1.9972178 , 0.9972178 , 0.983748  , 0.97456683, 0.94082557,
       0.93865616, 0.56676307, 0.54614658, 0.48724931, 0.2578954 ,
       0.21217093, 0.0888778 , 0.08882896, 0.02345967])